### PR TITLE
update to latest purescript-strings, fix all versions in bower

### PR DESCRIPTION
**Pull request by jdegoes**
Review / merge by @joneshf.

Current version is `0.2.2`, this API is compatible so could be a patch fix `0.2.3`.

### CODE REVIEW

**Comment by joneshf** [comment]
Thanks.

**Comment by joneshf** [comment]
I'll push a tag when i get home.

**Comment by jdegoes** [comment]
@joneshf  Bump on the new version.

**Comment by joneshf** [comment]
Up now, sorry.

**Pull request merged**
